

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_save_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_img.setGeometry(QtCore.QRect(860, 30, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_save_img.setFont(font)
        self.pushButton_save_img.setObjectName("pushButton_save_img")
        self.pushButton_choose_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose_img.setGeometry(QtCore.QRect(20, 30, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_choose_img.setFont(font)
        self.pushButton_choose_img.setObjectName("pushButton_choose_img")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 391, 231))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_find = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_find.setGeometry(QtCore.QRect(20, 50, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_find.setFont(font)
        self.pushButton_find.setObjectName("pushButton_find")
        self.pushButton_polylines = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_polylines.setGeometry(QtCore.QRect(20, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_polylines.setFont(font)
        self.pushButton_polylines.setObjectName("pushButton_polylines")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(125, 29, 260, 145))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnWidth(0, 200)  # 设置第一列列宽
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 110, 591, 231))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 351, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_moments = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_moments.setFont(font)
        self.pushButton_moments.setObjectName("pushButton_moments")
        self.gridLayout.addWidget(self.pushButton_moments, 0, 0, 1, 1)
        self.pushButton_area = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_area.setFont(font)
        self.pushButton_area.setObjectName("pushButton_area")
        self.gridLayout.addWidget(self.pushButton_area, 0, 1, 1, 1)
        self.pushButton_length = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_length.setFont(font)
        self.pushButton_length.setObjectName("pushButton_length")
        self.gridLayout.addWidget(self.pushButton_length, 0, 2, 1, 1)
        self.pushButton_approxPolyDP = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_approxPolyDP.setFont(font)
        self.pushButton_approxPolyDP.setObjectName("pushButton_approxPolyDP")
        self.gridLayout.addWidget(self.pushButton_approxPolyDP, 1, 0, 1, 1)
        self.pushButton_convexHull = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_convexHull.setFont(font)
        self.pushButton_convexHull.setObjectName("pushButton_convexHull")
        self.gridLayout.addWidget(self.pushButton_convexHull, 1, 1, 1, 1)
        self.pushButton_boundingRect = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_boundingRect.setFont(font)
        self.pushButton_boundingRect.setObjectName("pushButton_boundingRect")
        self.gridLayout.addWidget(self.pushButton_boundingRect, 1, 2, 1, 1)
        self.pushButton_minEnclosingCircle = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_minEnclosingCircle.setFont(font)
        self.pushButton_minEnclosingCircle.setObjectName("pushButton_minEnclosingCircle")
        self.gridLayout.addWidget(self.pushButton_minEnclosingCircle, 2, 0, 1, 1)
        self.pushButton_fitEllipse = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_fitEllipse.setFont(font)
        self.pushButton_fitEllipse.setObjectName("pushButton_")
        self.gridLayout.addWidget(self.pushButton_fitEllipse, 2, 1, 1, 1)
        self.pushButton_minAreaRect = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_minAreaRect.setFont(font)
        self.pushButton_minAreaRect.setObjectName("pushButton_minAreaRect")
        self.gridLayout.addWidget(self.pushButton_minAreaRect, 2, 2, 1, 1)
        self.pushButton_fitLine = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_fitLine.setFont(font)
        self.pushButton_fitLine.setObjectName("pushButton_fitLine")
        self.gridLayout.addWidget(self.pushButton_fitLine, 3, 0, 1, 1)
        self.pushButton_minEnclosingTriangle = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_minEnclosingTriangle.setFont(font)
        self.pushButton_minEnclosingTriangle.setObjectName("pushButton_minEnclosingTriangle")
        self.gridLayout.addWidget(self.pushButton_minEnclosingTriangle, 3, 1, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(360, 30, 231, 191))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_result = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_result.setGeometry(QtCore.QRect(10, 10, 4000, 4000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_result.setFont(font)
        self.label_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_result.setObjectName("label_result")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 350, 450, 400))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_source_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_source_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_source_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_source_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_source_img.setObjectName("label_source_img")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(540, 350, 450, 400))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_dealt_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_dealt_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_dealt_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_dealt_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_dealt_img.setObjectName("label_dealt_img")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像轮廓检测"))
        self.pushButton_save_img.setText(_translate("MainWindow", "保存图片"))
        self.pushButton_choose_img.setText(_translate("MainWindow", "选择图片"))
        self.groupBox.setTitle(_translate("MainWindow", "图像轮廓查找"))
        self.pushButton_find.setText(_translate("MainWindow", "查找轮廓"))
        self.pushButton_polylines.setText(_translate("MainWindow", "绘制轮廓"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "轮廓类型"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "轮廓个数"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "层次类型"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "查找结果"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("MainWindow", "图像轮廓特征"))
        self.pushButton_moments.setText(_translate("MainWindow", "轮廓的矩"))
        self.pushButton_area.setText(_translate("MainWindow", "轮廓面积"))
        self.pushButton_length.setText(_translate("MainWindow", "轮廓长度"))
        self.pushButton_approxPolyDP.setText(_translate("MainWindow", "近似多边形"))
        self.pushButton_convexHull.setText(_translate("MainWindow", "轮廓的凸包"))
        self.pushButton_boundingRect.setText(_translate("MainWindow", "直边界矩形"))
        self.pushButton_minEnclosingCircle.setText(_translate("MainWindow", "最小外包圆"))
        self.pushButton_fitEllipse.setText(_translate("MainWindow", "拟合椭圆"))
        self.pushButton_minAreaRect.setText(_translate("MainWindow", "旋转矩形"))
        self.pushButton_fitLine.setText(_translate("MainWindow", "拟合直线"))
        self.pushButton_minEnclosingTriangle.setText(_translate("MainWindow", "最小外包三角形"))
        self.label_result.setText(_translate("MainWindow", "结果显示"))
        self.label_source_img.setText(_translate("MainWindow", "原图像"))
        self.label_dealt_img.setText(_translate("MainWindow", "处理后图像"))
