"""
@Auth ： youngZ
@File ：featureMatchingUI.py
图像特征匹配UI
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_save_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_img.setGeometry(QtCore.QRect(1270, 30, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_save_img.setFont(font)
        self.pushButton_save_img.setObjectName("pushButton_save_img")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(470, 350, 450, 400))
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setWidgetResizable(False)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, -377, 4000, 4000))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.label_select_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_select_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_select_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_select_img.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_select_img.setObjectName("label_select_img")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(950, 350, 450, 400))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_dealt_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_dealt_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_dealt_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_dealt_img.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_dealt_img.setObjectName("label_dealt_img")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 50, 700, 260))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_violate_m = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_violate_m.setGeometry(QtCore.QRect(40, 150, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_violate_m.setFont(font)
        self.pushButton_violate_m.setObjectName("pushButton_violate_m")
        self.pushButton_flann = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flann.setGeometry(QtCore.QRect(480, 150, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_flann.setFont(font)
        self.pushButton_flann.setObjectName("pushButton_flann")
        self.pushButton_choose_p = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_choose_p.setGeometry(QtCore.QRect(40, 70, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_choose_p.setFont(font)
        self.pushButton_choose_p.setObjectName("pushButton_choose_p")
        self.pushButton_choose_s = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_choose_s.setGeometry(QtCore.QRect(260, 70, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_choose_s.setFont(font)
        self.pushButton_choose_s.setObjectName("pushButton_choose_s")
        self.pushButton_violate_k = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_violate_k.setGeometry(QtCore.QRect(260, 150, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_violate_k.setFont(font)
        self.pushButton_violate_k.setObjectName("pushButton_violate_k")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clear.setGeometry(QtCore.QRect(480, 70, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 350, 450, 400))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_source_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_source_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_source_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_source_img.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_source_img.setObjectName("label_source_img")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像特征匹配"))
        self.pushButton_save_img.setText(_translate("MainWindow", "保存图片"))
        self.label_select_img.setText(_translate("MainWindow", "训练图像"))
        self.label_dealt_img.setText(_translate("MainWindow", "结果图像"))
        self.groupBox_3.setTitle(_translate("MainWindow", "图像特征匹配"))
        self.pushButton_violate_m.setText(_translate("MainWindow", "暴力匹配(Match)"))
        self.pushButton_flann.setText(_translate("MainWindow", "FLANN匹配"))
        self.pushButton_choose_p.setText(_translate("MainWindow", "选择训练图像"))
        self.pushButton_choose_s.setText(_translate("MainWindow", "选择查询图像"))
        self.pushButton_violate_k.setText(_translate("MainWindow", "暴力匹配(knnMatch)"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空所有图像"))
        self.label_source_img.setText(_translate("MainWindow", "查询图像"))
