"""
@Auth ： youngZ
@File ：histogramEqualizationUI.py
直方图均衡化UI
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 320, 211))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_hist = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_hist.setGeometry(QtCore.QRect(20, 60, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_hist.setFont(font)
        self.pushButton_hist.setObjectName("pushButton_hist")
        self.pushButton_calcHist = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_calcHist.setGeometry(QtCore.QRect(180, 60, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_calcHist.setFont(font)
        self.pushButton_calcHist.setObjectName("pushButton_calcHist")
        self.pushButton_calcHist_mask = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_calcHist_mask.setGeometry(QtCore.QRect(20, 120, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_calcHist_mask.setFont(font)
        self.pushButton_calcHist_mask.setObjectName("pushButton_calcHist_mask")
        self.pushButton_NumPy = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_NumPy.setGeometry(QtCore.QRect(180, 120, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_NumPy.setFont(font)
        self.pushButton_NumPy.setObjectName("pushButton_NumPy")
        self.pushButton_choose_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose_img.setGeometry(QtCore.QRect(20, 30, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_choose_img.setFont(font)
        self.pushButton_choose_img.setObjectName("pushButton_choose_img")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 110, 311, 211))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_equalizeHist = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_equalizeHist.setGeometry(QtCore.QRect(10, 60, 290, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_equalizeHist.setFont(font)
        self.pushButton_equalizeHist.setObjectName("pushButton_equalizeHist")
        self.pushButton_createCLAHE = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_createCLAHE.setGeometry(QtCore.QRect(10, 120, 290, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_createCLAHE.setFont(font)
        self.pushButton_createCLAHE.setCheckable(False)
        self.pushButton_createCLAHE.setAutoRepeat(False)
        self.pushButton_createCLAHE.setAutoExclusive(False)
        self.pushButton_createCLAHE.setObjectName("pushButton_createCLAHE")
        self.pushButton_save_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_img.setGeometry(QtCore.QRect(860, 30, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_save_img.setFont(font)
        self.pushButton_save_img.setObjectName("pushButton_save_img")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 350, 450, 400))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_source_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_source_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_source_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_source_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_source_img.setObjectName("label_source_img")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(550, 350, 450, 400))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_dealt_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_dealt_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_dealt_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_dealt_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_dealt_img.setObjectName("label_dealt_img")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(690, 110, 280, 211))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_NumPy_double = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_NumPy_double.setGeometry(QtCore.QRect(50, 60, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_NumPy_double.setFont(font)
        self.pushButton_NumPy_double.setObjectName("pushButton_NumPy_double")
        self.pushButton_OpenCV_double = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_OpenCV_double.setGeometry(QtCore.QRect(50, 120, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_OpenCV_double.setFont(font)
        self.pushButton_OpenCV_double.setObjectName("pushButton_OpenCV_double")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "直方图处理"))
        self.groupBox.setTitle(_translate("MainWindow", "直方图基础"))
        self.pushButton_hist.setText(_translate("MainWindow", "绘制直方图"))
        self.pushButton_calcHist.setText(_translate("MainWindow", "查找直方图"))
        self.pushButton_calcHist_mask.setText(_translate("MainWindow", "掩膜直方图"))
        self.pushButton_NumPy.setText(_translate("MainWindow", "NumPy直方图"))
        self.pushButton_choose_img.setText(_translate("MainWindow", "选择图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "直方图均衡化"))
        self.pushButton_equalizeHist.setText(_translate("MainWindow", "普通直方图均衡化"))
        self.pushButton_createCLAHE.setText(_translate("MainWindow", "限制对比度自适应直方图均衡化"))
        self.pushButton_save_img.setText(_translate("MainWindow", "保存图片"))
        self.label_source_img.setText(_translate("MainWindow", "原图像"))
        self.label_dealt_img.setText(_translate("MainWindow", "直方图"))
        self.groupBox_3.setTitle(_translate("MainWindow", "二维直方图"))
        self.pushButton_NumPy_double.setText(_translate("MainWindow", "NumPy二维直方图"))
        self.pushButton_OpenCV_double.setText(_translate("MainWindow", "OpenCV二维直方图"))


