"""
@Auth ： youngZ
@File ：makeImageMaskUI.py
创建图像掩膜处理UI
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_save_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_img.setGeometry(QtCore.QRect(860, 20, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_save_img.setFont(font)
        self.pushButton_save_img.setObjectName("pushButton_save_img")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 80, 350, 240))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Normask = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Normask.setGeometry(QtCore.QRect(110, 170, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Normask.setFont(font)
        self.pushButton_Normask.setObjectName("pushButton_Normask")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 331, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(550, 340, 450, 400))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_dealt_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_dealt_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_dealt_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_dealt_img.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_dealt_img.setObjectName("label_dealt_img")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.pushButton_choose_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose_img.setGeometry(QtCore.QRect(20, 20, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_choose_img.setFont(font)
        self.pushButton_choose_img.setObjectName("pushButton_choose_img")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 340, 450, 400))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 4000, 4000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_source_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_source_img.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.label_source_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_source_img.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_source_img.setObjectName("label_source_img")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 80, 521, 240))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_mask = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_mask.setGeometry(QtCore.QRect(10, 180, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_mask.setFont(font)
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.label_message = QtWidgets.QLabel(self.groupBox_2)
        self.label_message.setGeometry(QtCore.QRect(10, 40, 180, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_message.setFont(font)
        self.label_message.setFrameShape(QtWidgets.QFrame.Box)
        self.label_message.setObjectName("label_message")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 40, 281, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 110, 50))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_width = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_width.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(150, 20, 110, 50))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_hight = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_hight.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.lineEdit_hight.setObjectName("lineEdit_hight")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(230, 140, 281, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 20, 110, 50))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_X = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_X.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(150, 20, 110, 50))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_Y = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Y.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "创建图像掩膜"))
        self.pushButton_save_img.setText(_translate("MainWindow", "保存图片"))
        self.groupBox.setTitle(_translate("MainWindow", "默认图像掩膜"))
        self.pushButton_Normask.setText(_translate("MainWindow", "创建默认掩膜"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:600; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400;\">声明</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400;\">默认掩膜大小为原图像的1/2</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400;\">默认掩膜的位置位于图像的正中心！</span></p></body></html>"))
        self.label_dealt_img.setText(_translate("MainWindow", "处理后图像"))
        self.pushButton_choose_img.setText(_translate("MainWindow", "选择图片"))
        self.label_source_img.setText(_translate("MainWindow", "原图像"))
        self.groupBox_2.setTitle(_translate("MainWindow", "自定义图像掩膜"))
        self.pushButton_mask.setText(_translate("MainWindow", "创建自定义掩膜"))
        self.label_message.setText(_translate("MainWindow", "当前图像信息"))
        self.groupBox_3.setTitle(_translate("MainWindow", "掩膜大小设置"))
        self.groupBox_4.setTitle(_translate("MainWindow", "宽度"))
        self.groupBox_5.setTitle(_translate("MainWindow", "高度"))
        self.groupBox_6.setTitle(_translate("MainWindow", "掩膜位置设置"))
        self.groupBox_7.setTitle(_translate("MainWindow", "X轴"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Y轴"))
